{
    'name': 'HR Employee Schedule Plus (Full Enterprise)',
    'version': '13.0.2.0.0',
    'category': 'Human Resources',
    'summary': 'Advanced employee scheduling: shifts, rotations, history, dashboard, notifications, attendance integration.',
    'description': """Full Enterprise HR Employee Schedule module for Odoo 13.

Features:
- Shift management (multiple shifts)
- Shift rotation engine
- Shift history tracking
- Email reminders and notifications
- Weekly automatic assignment cron
- Shift conflict validator
- Multi-shift per employee support
- Bulk import/export
- PDF report of schedules
- Approval workflow for shift changes
""",
    'author': 'Generated by ChatGPT for user',
    'depends': ['hr', 'hr_attendance', 'mail', 'board', 'web'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/mail_template.xml',
        'data/ir_cron.xml',
        'views/menus.xml',
        'views/hr_shift_views.xml',
        'views/hr_shift_kanban.xml',
        'views/hr_employee_views.xml',
        'views/hr_shift_history_views.xml',
        'views/wizard_bulk_assign_shift_views.xml',
        'views/wizard_import_shifts_views.xml',
        'views/res_config_settings_views.xml',
        'views/hr_shift_dashboard.xml',
        'reports/shift_report.xml',
    ],
    'installable': True,
    'application': True,
}
